### ISSUE TITLE
upstream_response_time chart in netdata helm chart

### ISSUE THREAD

**Issue by Peggy4444** [netdata/helmchart#100]
Hi,
I want to enable `upstream_response_time` in netdata using helm chart (k8s). I have enabled `go.d` plugin in values.yaml. 
Then using `./edit-config go.d.conf` on the netdata_master_0 pod, I have explicitly enabled weblog module `web_log: yes`. How can I restart netdata now to see the new charts?

I have also installed Nginx with helm chart.
Is there any other configuration I need to do in order to get the chart in the UI?

**Comment by ilyam8** [comment]
hi

@Peggy4444 do you know where are nginx logs? if they are on a system

> https://kubernetes.io/docs/concepts/cluster-administration/logging/#logging-at-the-node-level

And nd has access to that file it is possible.

Unfortunately you need to configurte all that manually, but we are working on making it more user friendly

**Comment by Peggy4444** [comment]
nginx logs are in `/var/log/nginx` directory of nginx pod. 
but I am not sure if netdata can access those logs. 
The configuration should be in netdata-master-0 pod? any slaves?

**Comment by Peggy4444** [comment]
total 8
drwxr-xr-x    1 www-data www-data      4096 Feb 24 12:47 .
drwxr-xr-x    1 www-data www-data      4096 Feb 21 19:27 ..
lrwxrwxrwx    1 www-data www-data        11 Feb 24 12:47 access.log -> /dev/stdout
lrwxrwxrwx    1 www-data www-data        11 Feb 24 12:47 error.log -> /dev/stderr

**Comment by ilyam8** [comment]
as you see it is stderr/stdour, so it is likely they are on the host sytem. If they are on the host system we can monitor them.

> Everything a containerized application writes to stdout and stderr is handled and redirected somewhere by a container engine.

> by a container engine

It is very likely the engine is docker in your case.

By default docker engine stores logs in

> /var/lib/docker/containers/[container-id]/[container-id]-json

Probably it means that we can monitor `nginx`/`apache` logs in k8s when we have service discovery + json parser. At least when it is docker and and node level logging ([there are options](https://kubernetes.io/docs/concepts/cluster-administration/logging/#logging-at-the-node-level)).

And it means that we can monitor `nginx/apache` from docker containers when we have docker service discovery module.

@cakrit

**Comment by ilyam8** [comment]
@Peggy4444 as for now - it is kind of impossible to use weblog in k8s.

As you see path contains container id, there is no way you will set it in module config manually

**Comment by ilyam8** [comment]
Nothing we can do atm, it is not this helmchart bug, i am closing the issue.

On the bright side - we are working on it and this issue is #100 🎉 Good number 😄

**Comment by Peggy4444** [comment]
I see, Thanks @ilyam8 

Just another question. Isn't there any other metric in netdata to monitor `upstream_latency_second` or related metrics? Not specifically for nginx and log monitoring

**Comment by ilyam8** [comment]
`weblog` just reads logs and collects vars from there

nginx vars:

> http://nginx.org/en/docs/varindex.html

```
$upstream_response_time

Time spent on receiving the response from the upstream server.
```

So it is app specific, we dont really monitor them - app exposes metrics, we collect and visualise them.

---

There are some plugins that do basic _measurements_. For example: `httpcheck`

> https://github.com/netdata/go.d.plugin/tree/master/modules/httpcheck#http-endpoint-monitoring-with-netdata
