### ISSUE TITLE
netdata/wget is not built for ARM

### ISSUE THREAD

**Issue by leflambeur** [netdata/helmchart#101]
I'm testing this on my k3s cluster on RPi - my slaves aren't starting as it relies on node/wget which is only built for amd64 (netdata though is built for ARM in of itself)

Is there any possibility of getting a wget image built for arm?

**Comment by ilyam8** [comment]
Hi @leflambeur 

Do you mean `netdata/wget`

https://github.com/netdata/helmchart/blob/962be5799a8a6f3473c2eaf07499f181cf397378/templates/daemonset.yaml#L59

?

Could you try to change it to `ilyam8/wget` and see if it works?

---

I googled for multi-arch images and found

> https://docs.docker.com/docker-for-mac/multi-arch/#build-and-run-multi-architecture-images

And build wget image for amd64/arm64/armv7

> https://hub.docker.com/r/ilyam8/wget/tags

**Comment by leflambeur** [comment]
> Do you mean netdata/wget

I did sorry I was going quick, I'll test it now

I wasn't sure if the netdata one was anything special and figured it's worth having an official one at least requested

**Comment by leflambeur** [comment]
![Screenshot 2020-05-26 at 14 33 06](https://user-images.githubusercontent.com/57944539/82906904-d86cb800-9f5d-11ea-912b-76a43516a132.png)


It's gone green :) - checked the dashboard and now it's there

![Screenshot 2020-05-26 at 14 32 53](https://user-images.githubusercontent.com/57944539/82906957-e91d2e00-9f5d-11ea-9388-a26d7641b857.png)

LGTM

**Comment by ilyam8** [comment]
@leflambeur 

switch to `netdata/wget` when https://github.com/netdata/docker-wget/pull/2 is merged

**Comment by leflambeur** [comment]
Watching it and will do, thanks for the quick turn around
