### ISSUE TITLE
Change master/slave to parent/child

### ISSUE THREAD

**Issue by joelhans** [netdata/helmchart#105]
Apologies if this is already in progress, but I wanted to be able to track the progress of this work, since it has quite a few implications for the k8s install doc (netdata/netdata#9364), and the k8s guide I'm also working on.

Related to netdata/netdata#9323 and netdata/netdata#9312

**Comment by ilyam8** [comment]
I assume this are breaking changes ([link](https://github.com/netdata/infra/blob/master/terraform/modules/k8s/netdata.tf))

@ncmans 

How do we handle it?

**Comment by ncmans** [comment]
@ilyam8 I've opened [an issue](https://github.com/netdata/infra/issues/667) for this in infra.

**Comment by ilyam8** [comment]
> Apologies if this is already in progress

Not wip, ill do it later today or tomorrow morning

**Comment by ilyam8** [comment]
@ncmans do we need to sync with https://github.com/netdata/infra/issues/667 or i can merge #106?

**Comment by ncmans** [comment]
> @ncmans do we need to sync with [netdata/infra#667](https://github.com/netdata/infra/issues/667) or i can merge #106?

The infra one is blocked by #106 so yes, you can merge 106.
