### ISSUE TITLE
Allow configuring deployment strategy

### ISSUE THREAD

**Issue by ncmans** [netdata/helmchart#113]
## Use Cases

- When making updates to a cluster with many netdata children, the update will take a very long time if they're updated one by one as is the default.

```
$ kubectl explain deployment.spec.strategy
KIND:     Deployment
VERSION:  extensions/v1beta1

RESOURCE: strategy <Object>

DESCRIPTION:
     The deployment strategy to use to replace existing pods with new ones.

     DeploymentStrategy describes how to replace existing pods with new ones.

FIELDS:
   rollingUpdate	<Object>
     Rolling update config params. Present only if DeploymentStrategyType =
     RollingUpdate.

   type	<string>
     Type of deployment. Can be "Recreate" or "RollingUpdate". Default is
     RollingUpdate.
```

**Comment by ilyam8** [comment]
Hi, we have `daemonset` and `statefulset`.

```cmd
1 ~ $ kubectl explain daemonset.spec.updateStrategy
KIND:     DaemonSet
VERSION:  extensions/v1beta1

RESOURCE: updateStrategy <Object>

DESCRIPTION:
     An update strategy to replace existing DaemonSet pods with new pods.

FIELDS:
   rollingUpdate	<Object>
     Rolling update config params. Present only if type = "RollingUpdate".

   type	<string>
     Type of daemon set update. Can be "RollingUpdate" or "OnDelete". Default is
     OnDelete.
```

explain is wrong, default is rollingUpdate

```cmd
0 ~ $ kubectl get ds/netdata-child -o go-template='{{.spec.updateStrategy.type}}{{"\n"}}' -n infra
RollingUpdate
```

Docs: https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/#daemonset-update-strategy

> OnDelete: With OnDelete update strategy, after you update a DaemonSet template, new DaemonSet pods will only be created when you manually delete old DaemonSet pods. This is the same behavior of DaemonSet in Kubernetes version 1.5 or before.

---

@ncmans what option changes would make update faster?

**Comment by ilyam8** [comment]
Ok, there is only one option - `daemonset.spec.updateStrategy.rollingUpdate.maxUnavailable`. It seems is what you need.

**Comment by ncmans** [comment]
> Ok, there is only one option - `daemonset.spec.updateStrategy.rollingUpdate.maxUnavailable`. It seems is what you need.

yes, exactly

**Comment by ncmans** [comment]
Most charts expose `updateStrategy` in their `values.yaml` file.

**Comment by ilyam8** [comment]
There is a bug in 1.23+, [this PR](https://github.com/netdata/netdata/pull/9520) fixes it.

1.23.0 and 1.23.1 is no-go in k8s.
