### ISSUE TITLE
Clarify requirement for "alarms" PVC

### ISSUE THREAD

**Issue by cakrit** [netdata/helmchart#114]
The "alarms" directory has a lot more than alarms now (claiming information, machine guid and we'll be adding more). It's becoming really necessary to have this directory survive pod restarts.

We basically have three options here:
- Provide more options for persistence, that distinguish between the various files stored under `/var/lib/netdata`. A `claim.d` directory is getting added there as well. I'm not fond of this option, because it means we'll need to always add new options and require new volumes every time we add a new file or directory there.
- Change the docs and the config files so that it's clear it's not just `alarms` that supposedly use the persistent storage for `/var/lib/netdata` but also key things like the machine guid, the claiming information and the health management API key. We strongly recommend that users persist this volume and only disable it if they don't want to use netdata cloud.
- Just demand at least one persistent volume, to be used for `/var/lib/netdata`, removing completely the option to disable it.

Would like to hear your views.

**Comment by ncmans** [comment]
I suggest:

- Having an optional single `data` persistent volume mounted under `/var/lib/netdata`.

**Comment by prologic** [comment]
@joelhans As this is really documentation IHMO, Would you be able to take this on? The last two points are what I think we need here in terms of documentation improvements. Also @ncmans 's point of just having one persistent volume is right right approach here as well.

**Comment by joelhans** [comment]
@prologic I can take a swing at this, sure. Once I see a PR for the volume, with the decision on whether to make it persistent or configurable, I'll follow up with an update to the docs.

**Comment by ilyam8** [comment]
i think it should be configurable, a valid use case - install `nd` agent daemonset **only** w/o any streaming and cloud. People use such setups - store metrics in some tsdb and use `nd` agents for real-time debugging.

**Comment by ncmans** [comment]
Yes, I believe a chunk of our users use the agent in a stateless config.

**Comment by cakrit** [comment]
If we do that, the info will be useful only or mainly if they export the data to another persistent storage. I created #116 for it.

**Comment by ncmans** [comment]
Given #116 is closed by a PR, is this issue resolved now?
