### ISSUE TITLE
Deployment error on Kubernetes

### ISSUE THREAD

**Issue by kevin-zhonghao** [netdata/helmchart#122]
Error is the following:
Netdata entrypoint script starting

```cmd
2020-08-04 22:49:16: netdata INFO  : MAIN : CONFIG: cannot load cloud config '/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults.
2020-08-04 22:49:16: netdata ERROR : MAIN : Ignoring host prefix '/host': path '/host' failed to stat() (errno 2, No such file or directory)
2020-08-04 22:49:16: netdata INFO  : MAIN : SIGNAL: Enabling reaper
2020-08-04 22:49:16: netdata INFO  : MAIN : process tracking enabled.
2020-08-04 22:49:16: netdata ERROR : MAIN : LISTENER: Invalid listen port 0 given. Defaulting to 19999. (errno 22, Invalid argument)
2020-08-04 22:49:16: netdata INFO  : MAIN : resources control: allowed file descriptors: soft = 1048576, max = 1048576
2020-08-04 22:49:16: netdata INFO  : MAIN : Out-Of-Memory (OOM) score is already set to the wanted value 1000
2020-08-04 22:49:16: netdata ERROR : MAIN : Cannot adjust netdata scheduling policy to idle (5), with priority 0. Falling back to nice. (errno 38, Function not implemented)
2020-08-04 22:49:16: netdata ERROR : MAIN : Cannot get my current process scheduling policy. (errno 38, Function not implemented)
2020-08-04 22:49:16: netdata INFO  : MAIN : netdata started on pid 1.
2020-08-04 22:49:16: netdata FATAL : MAIN : Cannot create directory '/var/lib/netdata/registry'. # : Invalid argument

2020-08-04 22:49:16: netdata INFO  : MAIN : EXIT: netdata prepares to exit with code 1...
2020-08-04 22:49:16: netdata INFO  : MAIN : EXIT: cleaning up the database...
2020-08-04 22:49:16: netdata INFO  : MAIN : Cleaning up database [0 hosts(s)]...
2020-08-04 22:49:16: netdata INFO  : MAIN : EXIT: all done - netdata is now exiting - bye bye...
```

Kubernetes version is v1.18.5,
Storageclass: Local,
here attached my storageclass and pv yaml:

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: netdata-database  #StorageClass name
provisioner: kubernetes.io/no-provisioner
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: netdata-alarms  #StorageClass name
provisioner: kubernetes.io/no-provisioner
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-database-netdata-parent
  labels:
    type: local
spec:
  storageClassName: netdata-database
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-alarms-netdata-parent
  labels:
    type: local
spec:
  storageClassName: netdata-alarms
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
```

**Comment by cakrit** [comment]
So it's:
- Not mounting `/host` : `2020-08-04 22:49:16: netdata ERROR : MAIN : Ignoring host prefix '/host': path '/host' failed to stat() (errno 2, No such file or directory)`
- Having problems writing the DB:  `2020-08-04 22:49:16: netdata FATAL : MAIN : Cannot create directory '/var/lib/netdata/registry'. # : Invalid argument`

Just to ensure there are no other problems, can you try modifying `parent.configs.netdata` so that it has `memory mode = ram`? That won't try to store anything to the disk. disable persistence too, so you can at least see netdata starting and displaying metrics. Once we know that's ok, we can focus on what's wrong with the storage. 

Even the error `LISTENER: Invalid listen port 0 given. Defaulting to 19999` doesn't make sense. Can we see all the differences between the default values.yaml and what you use to start it?

**Comment by ncmans** [comment]
@kevin-zhonghao can you please provide us with your `helm install` command and/or helm values you passed to chart so we can try to reproduce it here.

**Comment by kevin-zhonghao** [comment]
@cakrit I modified "parent.configs.netdata" and make "memory mode = ram", but it showed the same error, nothing changed. Here attached my values.yaml:
replicaCount: 1

image:
  repository: netdata/netdata
  tag: v1.23.2
  pullPolicy: Always

sd:
  repository: netdata/agent-sd
  tag: v0.1.0
  pullPolicy: Always
  child:
    enabled: true
    configmap:
      name: netdata-child-sd-config-map
      key: config.yml
      # if 'from' is {} the ConfigMap is not generated
      from:
        file: sdconfig/child.yml
        value: {}
    resources: {}
    # limits:
    #  cpu: 50m
    #  memory: 60Mi
    # requests:
    #  cpu: 50m
    #  memory: 60Mi

sysctlImage:
  enabled: false
  repository: alpine
  tag: latest
  pullPolicy: Always
  command: []
  resources: {}

service:
  type: ClusterIP
  port: 19999
  # Use a static loadBalancerIP. Only to be used with type LoadBalancer
  # loadBalancerIP: 10.0.1.69

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - netdata.k8s.local
#  tls:
#    - secretName: netdata-tls
#      hosts:
#        - netdata.k8s.local

rbac:
  create: true
  pspEnabled: true

serviceAccount:
  create: true
  name: netdata


parent:
  resources: {}
    # limits:
    #  cpu: 4
    #  memory: 4096Mi
    # requests:
    #  cpu: 4
    #  memory: 4096Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  priorityClassName: ""

  env: {}
    # To disable anonymous statistics:
    # DO_NOT_TRACK: 1

  podLabels: {}

  podAnnotations: {}

  database:
    persistence: true
    # Set '-' as the storageclass to get a volume from the default storage class.
    storageclass: netdata-database
    #storageclass: "-"
    volumesize: 2Gi

  alarms:
    persistence: true
    # Set '-' as the storageclass to get a volume from the default storage class.
    storageclass: netdata-alarms
    #storageclass: "-"
    volumesize: 100Mi

  configs:
    stream:
      enabled: true
      path: /etc/netdata/stream.conf
      data: |
        [11111111-2222-3333-4444-555555555555]
          enabled = yes
          history = 3600
          default memory mode = save
          health enabled by default = auto
          allow from = *
    netdata:
      enabled: true
      path: /etc/netdata/netdata.conf
      data: |
        [global]
          memory mode = ram
          bind to = 0.0.0.0:19999
        [plugins]
          cgroups = no
          tc = no
          enable running new plugins = no
          check for new plugins every = 72000
          python.d = no
          charts.d = no
          go.d = no
          node.d = no
          apps = no
          proc = no
          idlejitter = no
          diskspace = no
    health:
      enabled: true
      path: /etc/netdata/health_alarm_notify.conf
      data: |
        SEND_EMAIL="NO"
        SEND_SLACK="YES"
        SLACK_WEBHOOK_URL=""
        DEFAULT_RECIPIENT_SLACK=""
        role_recipients_slack[sysadmin]="${DEFAULT_RECIPIENT_SLACK}"
        role_recipients_slack[domainadmin]="${DEFAULT_RECIPIENT_SLACK}"
        role_recipients_slack[dba]="${DEFAULT_RECIPIENT_SLACK}"
        role_recipients_slack[webmaster]="${DEFAULT_RECIPIENT_SLACK}"
        role_recipients_slack[proxyadmin]="${DEFAULT_RECIPIENT_SLACK}"
        role_recipients_slack[sitemgr]="${DEFAULT_RECIPIENT_SLACK}"
    example:
      enabled: false
      path: /etc/netdata/health.d/example.conf
      data: |
        alarm: example_alarm1
          on: example.random
        every: 2s
        warn: $random1 > (($status >= $WARNING)  ? (70) : (80))
        crit: $random1 > (($status == $CRITICAL) ? (80) : (90))
        info: random
          to: sysadmin

child:
  enabled: true

  updateStrategy: {}
    # type: RollingUpdate
    # rollingUpdate:
    #   maxUnavailable: 1

  resources: {}
    # limits:
    #  cpu: 4
    #  memory: 4096Mi
    # requests:
    #  cpu: 4
    #  memory: 4096Mi

  nodeSelector: {}

  tolerations:
    - operator: Exists
      effect: NoSchedule

  affinity: {}

  priorityClassName: ""

  podLabels: {}

  podAnnotationAppArmor:
    enabled: true

  podAnnotations: {}

  persistUniqueID: true

  configs:
    netdata:
      enabled: true
      path: /etc/netdata/netdata.conf
      data: |
        [global]
          memory mode = none
        [health]
          enabled = no
    stream:
      enabled: true
      path: /etc/netdata/stream.conf
      data: |
        [stream]
          enabled = yes
          destination = netdata:19999
          api key = 11111111-2222-3333-4444-555555555555
          timeout seconds = 60
          buffer size bytes = 1048576
          reconnect delay seconds = 5
          initial clock resync iterations = 60
    go.d:
      enabled: true
      path: /etc/netdata/go.d.conf
      data: |
        modules:
          apache: yes
          bind: yes
          freeradius: yes
          lighttpd: yes
          mysql: yes
          nginx: yes
          openvpn: yes
          phpfpm: yes
          rabbitmq: yes
    kubelet:
      enabled: true
      path: /etc/netdata/go.d/k8s_kubelet.conf
      data: |
        update_every: 1
        autodetection_retry: 0
        jobs:
          - url: http://127.0.0.1:10255/metrics
          - url: https://localhost:10250/metrics
            tls_skip_verify: yes
    kubeproxy:
      enabled: true
      path: /etc/netdata/go.d/k8s_kubeproxy.conf
      data: |
        update_every: 1
        autodetection_retry: 0
        jobs:
          - url: http://127.0.0.1:10249/metrics

  env: {}
    # To disable anonymous statistics:
    # DO_NOT_TRACK: 1

**Comment by kevin-zhonghao** [comment]
@ncmans  The cmd I used is "helm install netdata ./netdata-helmchart". The values.yaml is in my previous comment. Thank you

**Comment by cakrit** [comment]
You still have `persistence: true` in your `values.yaml` @kevin-zhonghao , try it without `persistence: false`, so we can make sure your netdata starts properly without it. 
While you're at it, set the following to ram as well:
```
[11111111-2222-3333-4444-555555555555]
...
default memory mode = save
```

Can you also look at https://github.com/netdata/helmchart/issues/123 and the minikube storage provisioner bug mentioned there (in case you're working with minikube as well)?

**Comment by kevin-zhonghao** [comment]
@cakrit  when I set up persistence:false and service.type:NodePort, I could reach the dashboard and see the metrics ~ thank you so much. I will close the issue

**Comment by cakrit** [comment]
I would still like us to figure out the root cause of your issues with persistence though @kevin-zhonghao , if you don't mind helping us trace it. Are you using minikube?

**Comment by cakrit** [comment]
Closing due to no response.

**Comment by DylanDKnight** [comment]
I seem to be having a similar issue; the node will show up in netdata cloud for around a minute and allow me to view the logs of the netdata before dropping off.

![netdatalogs](https://user-images.githubusercontent.com/17187287/95006396-0ba21080-05fc-11eb-94d2-0af38cdaca35.PNG)

Then it will switch to UNREACHABLE:

![unreachable](https://user-images.githubusercontent.com/17187287/95006413-342a0a80-05fc-11eb-93cb-63fe76c13539.PNG)

Then when it comes back up, it shows the gap in metrics:

![drops](https://user-images.githubusercontent.com/17187287/95006447-75bab580-05fc-11eb-9a37-65ba940a4acd.PNG)


I have attached the logs here: https://gist.github.com/DylanDKnight/7c9d73459eb64211d4298a65d14d11a2

That is the Helm install command I am using; it gets me up time for a few minutes.

```
helm install \
  --set parent.resources.limits.cpu=1 \
  --set parent.resources.requests.cpu=1 \
  --set parent.resources.limits.memory=1Gi \
  --set parent.resources.requests.memory=1Gi \
  --set child.resources.limits.cpu=1 \
  --set child.resources.requests.cpu=1 \
  --set child.resources.limits.memory=1Gi \
  --set child.resources.requests.memory=1Gi \
  --set parent.database.persistence=true \
  --set parent.alarms.persistence=true \
  --set parent.claiming.enabled=true \
  --set service.port=19998 \
  --set parent.claiming.token="TOKEN" \
  --set parent.claiming.rooms="ROOM" \
  netdata ./netdata-helmchart/charts/netdata
```

I seem to have to use
`./netdata-helmchart/charts/netdata,` 
if I use 
`helm install netdata ./netdata-helmchart`
I get
`Error: validation: chart.metadata is required`

Any help would be appreciated
