### ISSUE TITLE
Default storage mode should be dbengine

### ISSUE THREAD

**Issue by cakrit** [netdata/helmchart#124]
We still have a couple of bugs to fix with the dbengine, but it should become the default memory mode very soon. We now use `save` in k8s, `dbengine` everywhere else.

**Comment by ncmans** [comment]
@cakrit @amoss do you have a list of bugs blocking this issue you can mention here

**Comment by cakrit** [comment]
1. Repeated dbengine global flushing errors for statsd  - https://github.com/netdata/netdata/issues/8384
2. Possibly Netdata master crashing at streaming set-up  - https://github.com/netdata/netdata/issues/9662 Not sure yet
3. Netdata taking 100% CPU - https://github.com/netdata/netdata/issues/9595
4. Netdata crashes every couple of days - https://github.com/netdata/netdata/issues/9581 mdstat collector has been written in such a way that it crashes the agent when using dbengine
5. Netdata fails to start - https://github.com/netdata/netdata/issues/9521 This one is only possible with persistent storage.

**Comment by cakrit** [comment]
These came from @mfundul

**Comment by mfundul** [comment]
6. Netdata master crashing at streaming set-up - https://github.com/netdata/netdata/issues/9662 Memory Corruption.

**Comment by cakrit** [comment]
The last step to enable this is:
- [ ] Use 1.25.0 in our own Netdata Cloud k8s cluster, with dbengine. Let's wipe out our old cache, to ensure we use the multihost DB engine
- [ ] Monitor it closely for ~2 weeks

If we have no issues then we make it default for all k8s installations.

@mfundul do you agree?

**Comment by mfundul** [comment]
> 
> 
> The last step to enable this is:
> 
>     * [ ]  Use 1.25.0 in our own Netdata Cloud k8s cluster, with dbengine. Let's wipe out our old cache, to ensure we use the multihost DB engine
> 
>     * [ ]  Monitor it closely for ~2 weeks
> 
> 
> If we have no issues then we make it default for all k8s installations.
> 
> @mfundul do you agree?

I expect ephemeral metrics to increase the memory footprint significantly. Moreover the CPU utilization will be an issue during startup of the agent. This will be addressed only when we utilize the SQLite POCs. Other than that I agree.

**Comment by knatsakis** [comment]
Unfortunately, I didn't know that we had to change the `dbengine disk space` option to `dbengine multihost disk space` in order to use the multihost db engine.

I have opened a PR for this now and we can start counting the two weeks as soon as it gets merged.

**Comment by mfundul** [comment]
> 
> 
> Unfortunately, I didn't know that we had to change the `dbengine disk space` option to `dbengine multihost disk space` in order to use the multihost db engine.
> 
> I have opened a PR for this now and we can start counting the two weeks as soon as it gets merged.

Yeah, backward compatibility is a pain. As long as there are old dbengine instances in `var/cache/netdata` then multihost-db is only used for new child nodes (not existing ones). So another thing to migrate to multihost-db is deleting the cache (and losing the history in the process).

**Comment by knatsakis** [comment]
> So another thing to migrate to multihost-db is deleting the cache (and losing the history in the process).

Thanks. I did that too. 🙇🏻 

I have merged and deployed multihost dbegnine today, so we can start counting two weeks from 29/09/2020

**Comment by knatsakis** [comment]
@cakrit as we have discussed there are performance issues with dbengine's metadata logs.

What do you think we should do here?

I think we should put this issue on ice until the above are resolved.

**Comment by cakrit** [comment]
If we can't have a default setting with a short enough retention to prevent performance issues, then I totally agree, we should wait for the metadata persistence improvements on the agent. k8s is special in that we know we'll have a parent node with a potentially very high number of child nodes streaming metrics to it, so an issue that doesn't normally appear on individual agents is magnified a lot.

**Comment by knatsakis** [comment]
Given the performance issues that we have been having with DBEngine I am inclined to say that a short retention will not help. We had a 6 hour retention and still had issues.

I am inclined to close this and open a new issue when the SQLite backend becomes available.

**Comment by kam1kaze** [comment]
hey, I've switched to dbengine a week ago and faced with the issue when the memory constantly growing. As I understand it's due to ephemeral metrics https://github.com/netdata/netdata/issues/9920. 

```
bash-5.0# strings -n5 /var/cache/netdata/dbengine/*.mlf | grep DIMENSION | wc -l
4982064
```

Are there any options to clear the old cache?

P.S. Also I do not see any dbengine related charts on the parent node. Should I manually enable it in config https://github.com/netdata/helmchart/blob/master/charts/netdata/values.yaml#L130 ?
