### ISSUE TITLE
Custom service-discovery for more services (e.g. Redis/Kafka/Elastic)? (With my attempts inside)

### ISSUE THREAD

**Issue by fzyzcjy** [netdata/helmchart#131]
Hi thanks for the wonderful netdata! I [know](https://learn.netdata.cloud/guides/monitor/kubernetes-k8s-netdata#service-discovery-services-running-inside-of-pods) netdata supports 22 apps for service discovery. However, I need to monitor things like Redis and Kafka, which is not in the list. I wonder **how to add my custom service-discovery**? 

Thanks!

My attempts:

1. I found that finally the generated go.d.yml is used by the go.d plugin code [here](https://github.com/netdata/go.d.plugin/blob/0c764a2f426627192e26299e7327960165cebf0a/cmd/godplugin/main.go#L67). Thus it seems non-Golang modules cannot be used? :/
2. I have another idea: **Can we support Prometheus metrics exporting**? Many apps like redis/kafka/... have prometheus exporter. Thus, if we support prometheus, we can happily collect a lot of apps even if the classical Netdata collectors cannot work.

**Comment by ncmans** [comment]
This seems like an issue for the @netdata/agent

**Comment by fzyzcjy** [comment]
OK I create an issue there https://github.com/netdata/netdata/issues/9774

**Comment by ilyam8** [comment]
@fzyzcjy as you saw discovery (in fact it is - watch config files, stop/start jobs in runtime) works only for go modules

> Redis/Kafka/Elastic

I plan to migrate elastic collector to go soon. Redis can be next.

> Can we support Prometheus metrics exporting

Yes, we can collect data from prometheus exporters. It is already ~ possible, we need to update service-discovery config file (add prometheus endpoint identification patterns).

**Comment by fzyzcjy** [comment]
@ilyam8 Thanks! By the way, in my humble opinion, the migration task only needs to, for instance, migrate the whole python.d/somethingelse.d to let it understand dynamic configurations, but not need to change things like redis/kafka/elastic exporters?

**Comment by ilyam8** [comment]
I am not sure what you mean by _exporters_, but we need to migrate/rewrite `*chart.py` files.

**Comment by fzyzcjy** [comment]
@ilyam8 Sorry for the inaccuracy. I mean, e.g. https://learn.netdata.cloud/docs/agent/collectors/python.d.plugin/redis

**Comment by ilyam8** [comment]
Yes, there is even [a WIP redis PR](https://github.com/netdata/go.d.plugin/pull/257)

i need to finish it

**Comment by fzyzcjy** [comment]
@ilyam8 Wow Redis will be rewritten in Go? That sounds wonderful!
