### ISSUE TITLE
Where should I put exporters (e.g. exporting to Prometheus format) - in the child or parent?

### ISSUE THREAD

**Issue by fzyzcjy** [netdata/helmchart#135]
I am a little confused about where should I put it.

My naive thoughts:

1. Maybe `child`? Because every node has a daemon of the "child", and we know NetData is very distributed and do not have centralized things (said in the netdata/netdata doc).
2. Maybe `parent`? Because the doc of this helmchart says child is headless and forward data to parent. But that contradicts with "netdata is not centralized", and I also do not see any code in `daemonset.yaml` related to "sending data to the parent"

Thanks very much!

**Comment by ilyam8** [comment]
Hi, as you know prometheus pulls metrics from an application. You configure a prometheus job, see

https://learn.netdata.cloud/docs/agent/exporting/prometheus#streaming-data-from-upstream-hosts

**Comment by fzyzcjy** [comment]
Thanks very much!
