### ISSUE TITLE
Stateful set requires serviceName to work

### ISSUE THREAD

**Issue by eranchetz** [netdata/helmchart#14]
Trying to deploy I am getting the following error:

```bash
$ kubectl apply -f statefulset.yaml
```

> error: error validating "statefulset.yaml": error validating data: ValidationError(StatefulSet.spec): missing required field "serviceName" in io.k8s.api.apps.v1beta2.StatefulSetSpec; if you choose to ignore these errors, turn validation off with --validate=false

According to the [spec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#statefulsetspec-v1-apps) this field is missing from the helm chart template.

**Comment by cakrit** [comment]
Hi @eranchetz, thanks for this.
I'll try adding it to see what happens. I should say though that I haven't tried using the config files individually with kubectl, I just let helm do its magic.

**Comment by cakrit** [comment]
The fix is in #15. I didn't see any problems in my tests. Can you check it? I'll also wait for @varyumin 's review to merge.
