### ISSUE TITLE
GPU Monitoring 

### ISSUE THREAD

**Issue by woojeonghoon** [netdata/helmchart#144]
When running with docker

docker run -d --name=netdata \
  -p 19999:19999 \
  -v /proc:/host/proc:ro \
  -v /sys:/host/sys:ro \
  -v /var/run/docker.sock:/var/run/docker.sock:ro \
  -e PGID=999 \
  -e NVIDIA_VISIBLE_DEVICES=all \
  -e DO_NOT_TRACK= \
  --cap-add SYS_PTRACE \
  --security-opt apparmor=unconfined \
  d34dc3n73r/netdata-glibc

I was able to see the GPU usage with the command "NVIDIA_VISIBLE_DEVICES=all".

![image](https://user-images.githubusercontent.com/49222476/93846393-db46a200-fcde-11ea-9316-b0657caa6194.png)

In Kubernetes environment
How can I check the GPU status?

**Comment by ncmans** [comment]
GPU monitoring for prometheus:

https://github.com/yahoojapan/gpu-monitoring-exporter

**Comment by woojeonghoon** [comment]
I solved it by correcting the image
