### ISSUE TITLE
Is it a Security problem? very general PodSecurityPolicy

### ISSUE THREAD

**Issue by fzyzcjy** [netdata/helmchart#148]
Hi thanks for this helm chart! When reviewing the code, I find the [psp.yaml](https://github.com/netdata/helmchart/blob/master/templates/psp.yaml) allows k8s pods to do a lot of things (actually almost everything!). I am a new learner to k8s, so I wonder whether this is ok, or will it cause serious security problems? Thanks very much!

P.S. I know netdata needs some privileges, but it seems that the psp requires a lot, such as `allowedCapabilities: - '*'`. IMHO Netdata will only use a small portion among them.

**Comment by ilyam8** [comment]
Related comment https://github.com/netdata/helmchart/pull/102#issuecomment-639086447

It would be nice if we have documented cluster role rules and psp.

**Comment by fzyzcjy** [comment]
@ilyam8 Thanks very much! Seems that there should be fewer rules, so will it be updated?

**Comment by ilyam8** [comment]
I think yes, we need to update it, what we have no is confusing.

**Comment by fzyzcjy** [comment]
@ilyam8 Thanks and looking forward to that update!

**Comment by ncmans** [comment]
We should only need:

- CAP_SYS_PTRACE
- Unconfined app-armour
- Passthrough `/proc`, `/sys`, `/`

Needs further investigation. We may be able to disable `privileged: true` in https://github.com/netdata/helmchart/blob/5fdfc74807c2a0ff707bb7ccd2ad0e425597e4b9/templates/deployment.yaml#L46

**Comment by M4itee** [comment]
@ilyam8 could you please test the app with the settings in the PR #239 ?

**Comment by M4itee** [comment]
due to #239  and #242 being merged - closing
