### ISSUE TITLE
pod has unbound immediate PersistentVolumeClaims.

### ISSUE THREAD

**Issue by nnthuanegany** [netdata/helmchart#197]
# Environment

- [Deploy Kubernetes monitoring with Netdata](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kubernetes)
- Digital Ocean Kubernetes

# Steps

**Step 1:** Install the Netdata Helm chart

```bash
helm repo add netdata https://netdata.github.io/helmchart/
helm install netdata netdata/netdata
```

**Step 2:** 

```bash
kubectl get services
# OK
```

**Step 3:**

```bash
kubectl get pods

# output
# netdata-parent-7c7c8ccfd-4x82s            0/1     Pending   0          4m57s
# Get details: pod has unbound immediate PersistentVolumeClaims.
```

**ERROR**:  `pod has unbound immediate PersistentVolumeClaims.`
 - netdata-parent-alarms
 - netdata-parent-database

# My solutions

Create `PersistentVolume` for each `PersistentVolumeClaims`.

==> **I hope it installs successfully with the command `helm install netdata netdata / netdata`**

**Comment by chrisDeFouRire** [comment]
I had the same issue with  the `netdata-parent-alarms` PVC only, chart version 3.6.9

It's because DO doesn't allow volumes < 1Gi. 
I fixed it with

```
parent:
  alarms:
    volumesize: 1Gi
```
in my override.yaml

**Comment by ilyam8** [comment]
Thanks, @chrisDeFouRire. You are correct! The allowed range is [1 GiB to 16 TiB](https://docs.digitalocean.com/products/volumes/). We either need to make a note for DO users in the readme or change the alarm volume size to 1Gi.

**Comment by ilyam8** [comment]
Ok, I see 1Gi is a minimal storage size for GKE too. But requesting less is not an error.

```cmd
$ kubectl get pvc alarms-netdata-parent-0 -o json | jq -r '"request=\(.spec.resources.requests), capacity=\(.status.capacity)"'
request={"storage":"100Mi"}, capacity={"storage":"1Gi"}
```

I guess we will change alarms pvc default then.
