### ISSUE TITLE
Add cpu and memory requests and limits to child sd containers

### ISSUE THREAD

**Issue by knatsakis** [netdata/helmchart#215]
SSIA

**Comment by ilyam8** [comment]
`sd` container needs
- CPU: a little, it doesn't do any CPU intensive operations
- memory: depends on the number of pods on the node and config maps (more objects => more memory). I think 150Mi is super safe.

<details>
<summary>See sd current memory usage in prod</summary>

```cmd
0 ~ $ kubectl -n mon top pods --containers=true -l app=netdata -l role=child | grep sd | awk '{print $NF}' | sort --reverse
37Mi
37Mi
36Mi
36Mi
34Mi
34Mi
33Mi
33Mi
33Mi
33Mi
32Mi
31Mi
31Mi
30Mi
30Mi
30Mi
29Mi
29Mi
29Mi
```

</details>

**Comment by KonstantinosPapazis** [comment]
Done
