### ISSUE TITLE
how to disable signup button? (or aclk)

### ISSUE THREAD

**Issue by 0xF4D3C0D3** [netdata/helmchart#223]
refer to https://github.com/netdata/netdata/issues/9561

it seems that /etc/netdata is readonly fs so I couldn't make use of edit-config for /etc/netdata/cloud.d
according to [disable-the-aclk](https://learn.netdata.cloud/docs/agent/aclk#disable-the-aclk) I have two options

but I think I can't go with the first way (if it can please let me know I'm new to k8s)
then, can I disable aclk at runtime?

more generally how can I add new or custom / plugins or confs?

thanks!

P.S. luckily I found this recent issue #217, however I couldn't find solution from there. if this requirement couldn't be satisfied at this point for some technical reason please let me know. I don't even know it's trivial or not though I'll try to contribute it :D

**Comment by ilyam8** [comment]
Hi, @0xF4D3C0D3. [Netdata image](https://hub.docker.com/r/netdata/netdata) compiled with ACLK support, that is why you see `SIGN IN TO CLOUT` button.

ACLK is [disabled by default](https://github.com/netdata/helmchart/blob/db228872b9bbf36426110a55860d71696cd350c1/charts/netdata/values.yaml#L303-L307).

**Comment by andrew-buzzni** [comment]
> Hi, @0xF4D3C0D3. [Netdata image](https://hub.docker.com/r/netdata/netdata) compiled with ACLK support, that is why you see `SIGN IN TO CLOUD` button.
> 
> ACLK (a connection to the Cloud) is [disabled by default](https://github.com/netdata/helmchart/blob/db228872b9bbf36426110a55860d71696cd350c1/charts/netdata/values.yaml#L303-L307).

Ooh thanks for reply, Ive misunderstood that. I thought that if I turn it off then sigin in or updates available button would be gone.

so what I was gonna do is to disable or to hide sign up button or ui like join community.

is it possible? maybe to do this, I need to make my own custom dashboard

**Comment by 0xF4D3C0D3** [comment]
> Hi, @0xF4D3C0D3. [Netdata image](https://hub.docker.com/r/netdata/netdata) compiled with ACLK support, that is why you see `SIGN IN TO CLOUD` button.
> 
> ACLK (a connection to the Cloud) is [disabled by default](https://github.com/netdata/helmchart/blob/db228872b9bbf36426110a55860d71696cd350c1/charts/netdata/values.yaml#L303-L307).

@ilyam8 
Ooh thanks for reply, Ive misunderstood that. I thought that if I turn it off then sign in or updates available button would be gone.

so what I was gonna do is to disable or to hide sign up button or ui like join community.

is it possible? maybe to do this, I need to make my own custom dashboard

**Comment by ilyam8** [comment]
>  I thought that if I turn it off then sign in or updates available button would be gone.

Ok, I see you need to [explicitly disable cloud](https://github.com/netdata/netdata/blob/59af90b08c705a66bdca7551b43257781db47711/web/api/web_api_v1.c#L976-L977) to get off that button:
 - create `cloud.conf`
 - set enabled to no in the global section

```yaml
[global]
  enabled = no
```

You can add it by adding a section to the [`configs`](https://github.com/netdata/helmchart/blob/db228872b9bbf36426110a55860d71696cd350c1/charts/netdata/values.yaml#L248) (⚠️ I've not tested it, but it supposed to work).


```yaml
    cloud:
      enabled: true
      path: var/lib/netdata/cloud.d/cloud.conf
      data: |
        [global]
          enabled = no
```

**Comment by 0xF4D3C0D3** [comment]
@ilyam8 

it totally works. thanks very much. have a nice day! :)

**Comment by Maddin-M** [comment]
I know this is a few years old, but I have applied the exact same settings, and can verify the existence of the cloud.conf file for both parent and child, but I still have the Sign In buttons in my instance. Did anything change there over the years?

**Comment by ilyam8** [comment]
@Maddin-M I think you can't disable it now.
