### ISSUE TITLE
Cannot establish websocket to api.netdata.cloud without IPv6

### ISSUE THREAD

**Issue by ohthehugemanatee** [netdata/helmchart#225]
To reproduce:
- Boot a system with `ipv6.disable=1` on the kernel command line
- Install netdata and claim to the cloud
- Observe failure logs:
```
ERROR : ACLK_Main : Libwebsockets: Unable to open socket
 (errno 97, Address family not supported by protocol)
```

There are two possible changes we could make to address this:

1) Document IPv6 in the requirements section of the relevant docs, OR
2) Gracefully fall back to IPv4.

**Comment by ilyam8** [comment]
Issue moved to [netdata/netdata #11327](https://github.com/netdata/netdata/issues/11327) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ilyam8** [comment]
Hi, @ohthehugemanatee. We've discussed it internally, it is a Netdata Agent bug, I moved the issue to netdata repository.
