### ISSUE TITLE
how to enable chrony collector?

### ISSUE THREAD

**Issue by withinboredom** [netdata/helmchart#249]
I'm trying to enable the [chrony](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/chrony/README.md) plugin via config maps. I was wondering if there is any documentation on how to do that?

**Comment by ilyam8** [comment]
Hi, @withinboredom. Chrony python collector uses [chronyc ](https://linux.die.net/man/1/chronyc) to gather metrics. I think that binary is not accessible from inside the Netdata container => python implementation doesn't work in k8s.

A quick google showed that there is [Native Go implementation of Chrony communication protocol v6](https://pkg.go.dev/github.com/facebookincubator/ntp/protocol/chrony). We need to check if we can use it and get the same metrics - if yes, then a chrony collector in go will do.
