### ISSUE TITLE
User reporting Netdata constantly crashing in Kubernetes

### ISSUE THREAD

**Issue by cakrit** [netdata/helmchart#263]
I will send this link to the user who just told me that they can't use Netdata in Kubernetes, as the pods keeps crashing, so he can provide additional details.

**Comment by ilyam8** [comment]
Fixed in https://github.com/netdata/netdata/pull/12512. Will be in today's nightlies.

**Comment by ilyam8** [comment]
Closing the issue, because it is fixed and not really k8s related.
