### ISSUE TITLE
RFC: Should we move this to https://github.com/helm/charts?

### ISSUE THREAD

**Issue by cakrit** [netdata/helmchart#27]
From what I know...

Pros:
 - Get feedback from the helm/charts maintainers to make improvements
 - More exposure & possibly more contributors
 
Cons:
 - Lose control of the process. We'll be depending on the helm/charts maintainers for merges
 - Any issues on this helm chart will be "lost" amongst irrelevant issues other charts there and on helm itself.

What do you think?

**Comment by kareem-elsayed** [comment]
One of the biggest issue to move to helm/charts this point.
I think we can keep it for now here once the chart becomes more stable we can then move to helm/charts
> * Any issues on this helm chart will be "lost" amongst irrelevant issues other charts there and on helm itself.

**Comment by cakrit** [comment]
Leaving it here for now.
