### ISSUE TITLE
Disable netdata-parent

### ISSUE THREAD

**Issue by tsunamaru** [netdata/helmchart#306]
Hello!

Is it possible to disable `netdata-parent` deployment? Is seems that in values.yaml `enabled` field (like in child and k8sstate) is ignored. Currently I do `k scale --replicas=0 deployment netdata-parent` every time I apply chart, but that is super inconvenient.

(context: I'm scraping metrics directly from `netdata-child` pods and thus I don't need `netdata-parent` deployment)

Thanks!

**Comment by ilyam8** [comment]
Hi, @tsunamaru. Added the option (parent.enabled) in #307.
