### ISSUE TITLE
Improved NOTES.txt

### ISSUE THREAD

**Issue by cakrit** [netdata/helmchart#32]
The instructions we give after installation can probably be smarter. I didn't know almost anything about k8s when I made changes on top of what @varyumin had written and I'm still not aware of the various set-ups people may have out there. If anyone has a better example to provide, or help improve this, I'd appreciate it

**Comment by josecv** [comment]
I think the [lamp](https://github.com/helm/charts/blob/61ce4c33c410f6a4f73713680885a20ac24e9be9/stable/lamp/templates/NOTES.txt#L5) chart is a good example of how you might want to give connection instructions. In particular, it instructs the user to go through the ingress controller (and create necessary DNS records) if they've configured one, or go through the LoadBalancer if the service is configured with one instead. Currently the [NOTES.txt](https://github.com/netdata/helmchart/blob/master/templates/NOTES.txt#L9) kind of assumes a LoadBalancer, when I think most people would want to be using a ClusterIP + Ingress Controller in production.

**Comment by cakrit** [comment]
There are if/then/else statements in the NOTES.txt, depending on `Values.ingress.enabled` and `Values.service.type`. The default is supposedly Ingress Controller + ClusterIP as you said, but it looks to me like the if/then/else doesn't cover the cases we have appropriately. Furthermore, we say absolutely nothing regarding the available options on the README. 

Now, I can go ahead and do tests on all possible permutations of `ingress.enabled` (true/false) and `service.type` (ClusterIP, NodePort, LoadBalancer), i.e. a total of 6 cases, to ensure that we have the cases documented in the README and the proper notes for each one. But are all 6 cases valid or does it for example make no sense to have NodePort with an ingress enabled? 

This is very tightly related to the questions in #36, so I'm closing that one as duplicate and will ensure we have the correct instructions on the README, instead of assuming that everyone will use the ingress controller.

**Comment by varyumin** [comment]
I don't think netdata must depend on ingress-controller.
On the first. You can turn off ingress-controller .ingress.enabled=false and use NodePort .service.type=NodePort (https://kubernetes.io/docs/concepts/services-networking/service/#nodeport ) the Kubernetes control plane will allocate a port from a range specified by --service-node-port-range flag (default: 30000-32767)
On the second. If you have another kind of ingress-controller. You can switch ingress.annotations.kubernetes.io/ingress.class=nginx to another (https://kubernetes.github.io/ingress-nginx/user-guide/multiple-ingress/). It can be gce, nginx, nginx-plus, traeffic or etc. Ingress-controller give abstraction above L7 Balancer

**Comment by M4itee** [comment]
as it is now, ingress is optional, service type is also configurable. Closing
