### ISSUE TITLE
No way to add custom annotations and labels to pods

### ISSUE THREAD

**Issue by josecv** [netdata/helmchart#33]
It would be cool to be able to annotate/label the netdata pods with custom annotations and labels. One thing that comes to mind, for example, is using annotations to make a [prometheus](https://prometheus.io/) server scrape netdata.

One way this could be done is to have `master.podLabels`, `master.podAnnotations`, `slave.podLabels` and `slave.podAnnotations` available in `values.yaml`. This would be consistent with how I've seen some other charts (e.g. the [postgresql](https://github.com/helm/charts/blob/master/stable/postgresql/README.md) chart) do it.

If this is of interest, I'd be happy to submit a PR implementing it 🙂

**Comment by cakrit** [comment]
Sounds great, I just don't get how exactly it would work. All I have to go on is https://docs.netdata.cloud/backends/prometheus/ which shows labels only in the prometheus configuration itself and I haven't worked with Prometheus myself. If I'm not mistaken, shouldn't netdata be modified to add those labels and annotations to the responses to the prometheus requests? e.g. to what you get from http://localhost:19999/api/v1/allmetrics?format=prometheus&prefix=nd&timestamps=no

**Comment by josecv** [comment]
Oh I'm thinking in terms of kubernetes [annotations](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/) and [labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/) as opposed to metric labels. These are generic pieces of metadata that go on the pods, and can be consumed by different applications on the cluster.

The prometheus example has to do with how, when prometheus is [configured to monitor a k8s cluster,](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config) it can be configured to process specific k8s annotations and labels on pods in specific ways. It can use these to keep, drop, or relabel metrics coming from pods.
This could be used to configure netdata pods as a prometheus target, or it could also be used to prometheus turn kubernetes labels into metric labels, extending the metric labels that netdata itself makes available.
