### ISSUE TITLE
Incompatible with current versions of k8s (1.25)

### ISSUE THREAD

**Issue by ohthehugemanatee** [netdata/helmchart#331]
The PodSecurityPolicy API has been [removed in 1.25](https://kubernetes.io/blog/2022/08/23/kubernetes-v1-25-release/#pod-security-changes), so this helm chart no longer works.

```
Error: UPGRADE FAILED: current release manifest contains removed kubernetes api(s) for this kubernetes version and it is therefore unable to build the kubernetes objects for performing the diff. error from kubernetes: unable to recognize "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
```

It's time to [migrate to Pod Security Admission](https://kubernetes.io/docs/tasks/configure-pod-container/migrate-from-psp/).

**Comment by ilyam8** [comment]
Hi, @ohthehugemanatee. PSP-related manifests are generated only if k8s version < 1.25 ([example](https://github.com/netdata/helmchart/blob/cec5f0cb03c364a92fde87fd4e32d7545f0666a4/charts/netdata/templates/psp.yaml#L1)). How did you get this error?

**Comment by ohthehugemanatee** [comment]
I just ran `helm upgrade -n netdata netdata netdata/netdata -f override.yaml` . Relevant versions from `kubectl version`:

```
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.25.6+k3s1
```

I've had netdata running for a long time on this cluster. Maybe it's complaining about an existing manifest?

**Comment by ohthehugemanatee** [comment]
... aaaaand I realized that I never updated the repo before the upgrade. Which is why it was pulling an old version of the manifest, and this whole Issue can be closed as PEBKAC. Thanks for your help. :)
