### ISSUE TITLE
Can't use ingressClassName

### ISSUE THREAD

**Issue by 0xF4D3C0D3** [netdata/helmchart#332]
https://github.com/netdata/helmchart/blob/cec5f0cb03c364a92fde87fd4e32d7545f0666a4/charts/netdata/values.yaml#L57-L73

When I use ingressClassName with kubernetes.io/ingress.class, I get error like [this](https://serverfault.com/a/1061592/963956) / `one or more objects failed to apply, reason: Ingress.extensions "netdata" is invalid: annotations.kubernetes.io/ingress.class: Invalid value: "alb": can not be set when the class field is also set
`

That's because kubernetes.io/ingress.class always has a default value

What should I do? Please help.. thanks

p.s. belows weren't working
```
annotations: {}
or
annotations: ~
```

**Comment by 0xF4D3C0D3** [comment]
well.. I've googled little more and found that this is actually helm's bug https://github.com/helm/helm/issues/5184

it should be controlled if I set the annotation as `null` but in recent version it doesn't work anymore

you can close this issue

**Comment by ilyam8** [comment]
Thanks for finding the problem, @0xF4D3C0D3!
