### ISSUE TITLE
Allow customizing volume type

### ISSUE THREAD

**Issue by MOZGIII** [netdata/helmchart#35]
My cluster only provide block PVs, can you allow using Block volume types?

**Comment by karuppiah7890** [comment]
I was just checking what block volume means. Are you talking about `volumeMode: Block` ?

**Comment by MOZGIII** [comment]
Yes.

**Comment by MOZGIII** [comment]
Here's a link to the documentation: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#raw-block-volume-support

**Comment by MOZGIII** [comment]
Actually, it might be a bit too difficult to support - I think there should be an intermediary in my cluster that claims `Block` volumes and provides `Filesystem` volumes instead... Yeah, that would be much better architecturally.

**Comment by MOZGIII** [comment]
It's easy to pass the value, however I'm not sure if the pod will be able to utilize the block volume. Block volumes presented as raw devices, and, as I understand, to use it for netdata's data, the pod will have to properly format and mount it. I don't think it should be solved at the level of this chart.

**Comment by karuppiah7890** [comment]
Ah okay! 👍
