### ISSUE TITLE
Doubt Regarding the Deployment.

### ISSUE THREAD

**Issue by andrebeltrami** [netdata/helmchart#36]
Hi all, 
I have an issue trying to do this Netdata Deployment. Please if anyone can help me, I really appreciated. 

I run `helm install --name my-release ./netdata`. However, the netdata-master pod stays with pending status. 

In the describe pods command, I can see this message. 
"pod has unbound immediate PersistentVolumeClaims"

I access the Netdata dashboard from the slaves, but the dashboard from the master I can't access. 

Any idea what I have to do?

Thanks. André

**Comment by cakrit** [comment]
Oh boy, are you using Google Cloud by any chance? I had spent half a day troubleshooting when this happened to me. Because I'm a newbie, I think that at the end I ended up deleting and recreating the storage I had set up on the Cloud Console. I hope some of the more seasoned people in this forum can provide a better solution. 

We do have the workaround of disabling persistent storage completely:
`master.database.persistence=false` and `slave.database.persistence=false` can be set, to disable persistenct completely. I just noticed that we don't have these two values on the `README.md`, though they do exist in values.yaml. Doing a change on the README.

**Comment by andrebeltrami** [comment]
Hi @cakrit, 
I don't use the Google Cloud. I will try to deploy the most simple environment, with netdata collecting the physical resources from Kubernetes Master and Slaves. 

I deactivate the persistent storage as you said, Thank you! The pods are started successfully but I don't see the metrics being collected. I cannot access the Master Netdata Dashboard. I attached the describe pods for the Master Pod. 

Only for information, my environment has only one Master and one Worker, I installed the helm via the snap, and I am using the Kubernetes v1.14. 

[describeMaster.txt](https://github.com/netdata/helmchart/files/3308644/describeMaster.txt)

**Comment by cakrit** [comment]
Check the [notes](https://github.com/netdata/helmchart/blob/master/templates/NOTES.txt) shown after the installation to see how you'll be able to access the UI via the nginx proxy. They are not great, I've requested some help in #32.

Marking this as a bug with help wanted as well, for the original issue of the unbound volume claims.

**Comment by andrebeltrami** [comment]
If I run `kubectl get services`. I have only two services, one for kubernetes and another one for netdata. I don't have the Nginx service. It's installed automatically via the helm netdata, or I need to configure it separated? 

After the helm netdata start, the output brings the notes that you said and these resources description:
I suppose it's necessary the nginx proxy or the v1beta1/Ingress is my ingress point to access the netdata master dashboard?

RESOURCES:
==> v1/ClusterRole
NAME                AGE
my-release-netdata  0s

==> v1/ClusterRoleBinding
NAME                AGE
my-release-netdata  0s

==> v1/ConfigMap
NAME                 DATA  AGE
netdata-conf-master  2     0s
netdata-conf-slave   5     0s

==> v1/DaemonSet
NAME           DESIRED  CURRENT  READY  UP-TO-DATE  AVAILABLE  NODE SELECTOR  AGE
netdata-slave  2        2        0      2           0          <none>         0s

==> v1/Pod(related)
NAME                 READY  STATUS             RESTARTS  AGE
netdata-master-0     0/1    ContainerCreating  0         0s
netdata-slave-5bs8z  0/1    ContainerCreating  0         0s
netdata-slave-n9pkc  0/1    ContainerCreating  0         0s

==> v1/Service
NAME     TYPE       CLUSTER-IP   EXTERNAL-IP  PORT(S)    AGE
netdata  ClusterIP  10.98.169.4  <none>       19999/TCP  0s

==> v1/ServiceAccount
NAME     SECRETS  AGE
netdata  1        0s

==> v1beta1/Ingress
NAME     HOSTS              ADDRESS  PORTS  AGE
netdata  netdata.k8s.local  80       0s

==> v1beta2/StatefulSet
NAME            READY  AGE
netdata-master  0/1    0s

**Comment by cakrit** [comment]
With minikube I was able to connect directly, but on Google cloud I just had to use the nginx ingress. The helm install command in the readme is supposed to install the nginx-ingress for you as well. Can you delete it, install it again and see the output helm? It looks like something didn't go well.

**Comment by andrebeltrami** [comment]
Hi guys, 
I tried to delete @cakrit, but the result is always the same.

NAME:   my-release
LAST DEPLOYED: Fri Jun 21 16:47:30 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ClusterRole
NAME                AGE
my-release-netdata  0s

==> v1/ClusterRoleBinding
NAME                AGE
my-release-netdata  0s

==> v1/ConfigMap
NAME                 DATA  AGE
netdata-conf-master  3     0s
netdata-conf-slave   5     0s

==> v1/DaemonSet
NAME           DESIRED  CURRENT  READY  UP-TO-DATE  AVAILABLE  NODE SELECTOR  AGE
netdata-slave  2        2        0      2           0          <none>         0s

==> v1/Pod(related)
NAME                 READY  STATUS             RESTARTS  AGE
netdata-master-0     0/1    ContainerCreating  0         0s
netdata-slave-nf9zj  0/1    ContainerCreating  0         0s
netdata-slave-q9nbl  0/1    ContainerCreating  0         0s

==> v1/Service
NAME     TYPE       CLUSTER-IP  EXTERNAL-IP  PORT(S)    AGE
netdata  ClusterIP  10.97.59.0  <none>       19999/TCP  0s

==> v1/ServiceAccount
NAME     SECRETS  AGE
netdata  1        0s

==> v1beta1/Ingress
NAME     HOSTS              ADDRESS  PORTS  AGE
netdata  netdata.k8s.local  80       0s

==> v1beta2/StatefulSet
NAME            READY  AGE
netdata-master  0/1    0s

The nginx ingress doesn't appear. However, the Netdata master is collecting the metrics I tested using the rest api on the netdata master pod <IP:19999>. I don't know why the nginx ingress port is not working. I can't access the netdata master dashboard externally, only locally.

**Comment by cakrit** [comment]
Hm... do this please:
`helm install stable/nginx-ingress`

I'll read up on the dependencies and what's supposed to happen. Maybe it's a step that we implied and we shouldn't have...

**Comment by cakrit** [comment]
Gents, it looks like we need a `requirements.yaml` with the `nginx-ingress` in it: https://github.com/helm/helm/blob/master/docs/helm/helm_dependency.md

I'll see if I can get to it soon, it should be a very easy PR for anyone who wants to hep.

**Comment by josecv** [comment]
FWIW I don't think most charts that have ingresses (e.g. [sonarqube](https://github.com/helm/charts/tree/master/stable/sonarqube), [lamp](https://github.com/helm/charts/tree/master/stable/lamp) or [concourse](https://github.com/helm/charts/tree/master/stable/concourse)) set up an explicit dependency to `nginx-ingress`. Probably this is because most users expect to manage the ingress controller as a separate install instead of as a dependency to any given chart, and different users might want to use different ingress controllers (e.g. [traefik](https://traefik.io/)

That said I don't think it's a problem as long as it's easy to disable the requirement via a [condition](https://helm.sh/docs/developing_charts/#tags-and-condition-fields-in-requirements-yaml) 🙂

**Comment by cakrit** [comment]
We will continue this in #32, because it's linked to the lack of proper documentation / instructions on how to access the master node.

**Comment by varyumin** [comment]
Can  I see render templates `helm template --name my-release ./netdata`? I don't think `netdata` must depend on ingress-controller. 
On the first. You can turn off ingress-controller ` .ingress.enabled=false` and use `NodePort` `.service.type=NodePort` (https://kubernetes.io/docs/concepts/services-networking/service/#nodeport ) `the Kubernetes control plane will allocate a port from a range specified by --service-node-port-range flag (default: 30000-32767)`
On the second. If you have another kind of ingress-controller. You can switch `ingress.annotations.kubernetes.io/ingress.class=nginx` to another (https://kubernetes.github.io/ingress-nginx/user-guide/multiple-ingress/). It can be gce, nginx, nginx-plus, traeffic or etc. Ingress-controller give abstraction above L7 Balancer
