### ISSUE TITLE
Add initialDelaySeconds to DaemonSet livenessProbe

### ISSUE THREAD

**Issue by fzyzcjy** [netdata/helmchart#366]
Otherwise when it runs on low-end devices, the probe may fail

**Comment by ilyam8** [comment]
Hi, @fzyzcjy. I made it configurable in #367 but didn't change the default value (0, no delay). Will it do? Or your suggestion is to make it configurable and make it not 0?

**Comment by fzyzcjy** [comment]
Sure, 0 LGTM as long as it is configurable
