### ISSUE TITLE
storedType not in values.yaml

### ISSUE THREAD

**Issue by data-dude** [netdata/helmchart#378]
Helm complains when trying to compare config.storedType because it's not defined in the values.yaml file.  We should add that to the default values.yaml file.  The docs mention storedType but it's not in the section with the different variables.

**Comment by ilyam8** [comment]
Hi. What is your helm version? If it [is < 3.8](https://github.com/netdata/helmchart/issues/368), I suggest upgrading.

**Comment by data-dude** [comment]
The latest tag is 3.7.x

**Comment by ilyam8** [comment]
I mean `helm version`, see #368.

**Comment by data-dude** [comment]
Oh OK

**Comment by ilyam8** [comment]
I made a PR that adds support for helm < 3.8 (#369), but it was closed. The [prerequisites](https://github.com/netdata/helmchart#prerequisites) section says that helm 3.8+ is required.

**Comment by data-dude** [comment]
Ok.  I don't mind upgrading though
