### ISSUE TITLE
Apparmor annotation still not taking affect

### ISSUE THREAD

**Issue by joell** [netdata/helmchart#40]
https://github.com/netdata/helmchart/blob/c0fa186ddcbd9be488309dbffb85d9f57b521ab8/templates/daemonset.yaml#L20

This annotation did not take affect in my case.  First off, it seems that the second `annotations` clause for `checksum/config` on line 28 below seems to stomp over the apparmor annotation.

After merging the two `annotations` clauses, I then got errors from K8S because the annotation reference a container name not found in the pod.  (The pod is named `netdata-slave` but the container within that pod is named `netdata`.)  I found it was necessary to change `/netdata-slave` to `/netdata`, after which everything worked.

In summary, the following change got things working for me:
```diff
--- a/templates/daemonset.yaml
+++ b/templates/daemonset.yaml
@@ -17,7 +17,8 @@ spec:
   template:
     metadata:
       annotations:
-        container.apparmor.security.beta.kubernetes.io/netdata-slave: unconfined
+        container.apparmor.security.beta.kubernetes.io/netdata: unconfined
+        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
       labels:
         app: {{ template "netdata.name" . }}
         release: {{ .Release.Name }}
@@ -25,8 +26,6 @@ spec:
 {{- with .Values.slave.podLabels }}
 {{ toYaml . | trim | indent 8 }}
 {{- end }}
-      annotations:
-        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
 {{- with .Values.slave.podAnnotations }}
 {{ toYaml . | trim | indent 8 }}
 {{- end }}
```

**Comment by cakrit** [comment]
@josecv and @charlieegan3 any comments on this? Should we do another PR to make the changes above?

**Comment by josecv** [comment]
@cakrit yup, with some minor adjustments -- basically the `with .Values.slave.podAnnotations` needs to be moved to be under checksum/config so that all annotations get merged together:

```
        container.apparmor.security.beta.kubernetes.io/netdata: unconfined
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
 {{- with .Values.slave.podAnnotations }}
 {{ toYaml . | trim | indent 8 }}
 {{- end }}
```

I'd also recommend having a way to turn off the appArmor annotation btw

**Comment by cakrit** [comment]
Feel free to make a PR gents. I'll be pretty swamped for the next week or two. Will try it if no one else has a go in the meantime.

**Comment by charlieegan3** [comment]
I've had a go at implementing this here: https://github.com/netdata/helmchart/pull/41

**Comment by joell** [comment]
I've commented on #41 but will here as well: The container name in the apparmor annotation still needs to be changed from `netdata-slave`.
