### ISSUE TITLE
linkerd-enabled namespace extra containers

### ISSUE THREAD

**Issue by cakrit** [netdata/helmchart#62]
: I'm trying to run netdata in a linkerd-enabled namespace and although the master picks up the mesh extra containers the slaves won't, how is that?

master
![Screenshot 2019-11-07 at 10 35 42](https://user-images.githubusercontent.com/12844/68377308-63b16800-014a-11ea-9849-8fc14ab53a0e.png)

slave
![Screenshot 2019-11-07 at 10 35 49](https://user-images.githubusercontent.com/12844/68377306-63b16800-014a-11ea-8c93-44e801b57b9b.png)

I even tried

```
    slave:
      podAnnotations:
        linkerd.io/inject: enabled
```

ref https://linkerd.io/2/features/proxy-injection/

_Originally posted by @masterkain in https://github.com/netdata/helmchart/issues/45#issuecomment-551000057_

**Comment by cakrit** [comment]
@masterkain you put a lot of unknown to me words in this one, so I'll ask for your patience to understand better what you mean. When you say 'the master picks up the mesh extra containers', what do you mean and how can I get what you show in your images? 

I will throw the guess that you're not seeing what you expect, because the slaves don't provide the 'service', we could even disable the web server on them completely, if we wanted. We only kept the web server running on the slaves, for two reasons: liveness probe and sanity tests from the command-line (e.g. wget http://localhost:19999/api/v1/info).  

The slaves stream their metrics to the master and you can access their charts from the master's UI menu on the top left. 

If I'm correctly reading how @varyumin did this, it starts with the selector at https://github.com/netdata/helmchart/blob/master/templates/service.yaml#L21

The ingress gets linked to that service etc.

If you're asking something completely different, let me know, I'll see if I can dig further.

**Comment by masterkain** [comment]
hello @cakrit no worries mine was just curiosity, I don't believe it might be strictly necessary to have the slaves in a mesh.

linkerd is an app mesh that injects proxy sidecars onto your pods.
it is possible for linkerd to apply automatically such proxy (for observability, etc.) if there's the special annotation on the pod namespace.

in my case I have netdata installed in the `netdata` namespace that has been modified to include the linkerd injection annotation, so every pod created in such namespace should have sidecar proxy.

however I noticed that only the master has that and I was more curious about how slave pods were created skipping the proxy injection.

**Comment by cakrit** [comment]
Ok then, closing and please comment if you need anything else. "not seeing all the requirements it needs to inject" may be related to what I wrote about the ingress, not sure.
