### ISSUE TITLE
Add our chart to the official charts repo

### ISSUE THREAD

**Issue by cakrit** [netdata/helmchart#72]
https://github.com/helm/charts has lists of Helm charts in various maturity levels. There are specific criteria that need to met, I think we meet all or most of them already. I would do a PR to that repo, as we do for DigitalOcean and update it whenever this chart changes.

**Comment by cakrit** [comment]
Motivation for this: More exposure for netdata.

**Comment by ncmans** [comment]
@Ferroin @prologic is this for you guys?

**Comment by prologic** [comment]
Yeap we'll do i!

**Comment by fzyzcjy** [comment]
Hi almost half a year has passed. Any progress?

**Comment by prologic** [comment]
See related [Issue](https://github.com/netdata/helmchart/issues/74)

**Comment by knatsakis** [comment]
This is now done: https://artifacthub.io/packages/helm/netdata/netdata (ArtifactHub is the successor to Helm Hub)
