### ISSUE TITLE
Apply for inclusion in Helm Hub

### ISSUE THREAD

**Issue by ncmans** [netdata/helmchart#78]
After we have a stable [helm repo](https://github.com/netdata/helmchart/issues/74), we should add it to [Helm Hub](https://github.com/helm/hub/blob/master/Repositories.md) for better visibility/searchability.

**Comment by fzyzcjy** [comment]
+1 It has been 4 months!

**Comment by prologic** [comment]
See related [Issue](https://github.com/netdata/helmchart/issues/74)

**Comment by knatsakis** [comment]
All done: https://artifacthub.io/packages/helm/netdata/netdata
