### ISSUE TITLE
Support claiming for Netdata cloud

### ISSUE THREAD

**Issue by cakrit** [netdata/helmchart#79]
Our Helm chart should permit claiming the nodes, so they can appear on Netdata cloud. We can do it [via options to the executable](https://github.com/netdata/netdata/blob/master/claim/README.md#netdata-agent-command-line).

I would do it only for the master pod right now. 

Not required for the cloud release, but it would be good if can dog food this one.

**Comment by ncmans** [comment]
Can think of one reasonable place to put it:
- Helm post install hook (agent can be kicked out and it won't be claimed until manually/re-install of the chart)

Alternatively, in a side car to claim on a loop.

**Comment by cakrit** [comment]
Since we can run netdata with command line options to do this, why not define an [init container](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-initialization/#create-a-pod-that-has-an-init-container) and use `values.yaml` to get the additional required options?

**Comment by ncmans** [comment]
> Since we can run netdata with command line options to do this, why not define an [init container](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-initialization/#create-a-pod-that-has-an-init-container) and use `values.yaml` to get the additional required options?

ye, that too — one behavior that can direct which method to use is: do we want to claim once, or ensure we stay claimed (even if the user removes the agent from the dashboard).

**Comment by cakrit** [comment]
>  one behavior that can direct which method to use is: do we want to claim once, or ensure we stay claimed (even if the user removes the agent from the dashboard).

Ah, excellent point! We haven't worked on un-claiming yet, we were going to do it after the release.

With the command-line solution: Right now, the claiming process will be repeated every time the pod is restarted, as long as the command line options are there. It doesn't matter if the [claiming directory](https://github.com/netdata/netdata/blob/master/claim/README.md#claiming-directory) under `/etc/netdata/claim` is persisted or not, it won't check. So we don't need to persist that volume at all (though we do need a certificate chain, if the node can't retrieve it).

**Comment by unixfox** [comment]
With the release of netdata cloud publicly I'm also interested into that feature in order to add my whole fleet of nodes in one go on the netdata cloud website.

**Comment by lgg42** [comment]
> Since we can run netdata with command line options to do this, why not define an [init container](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-initialization/#create-a-pod-that-has-an-init-container) and use `values.yaml` to get the additional required options?

I vote for the init container. Our cluster is very dynamic so nodes comes and goes. Ideally the chart is installed once and updated once in a while but every time a netdata slave starts in a new node claiming could be done in a init container.

**Comment by cakrit** [comment]
Blocks https://github.com/netdata/netdata/issues/8779

**Comment by knatsakis** [comment]
Hi,

I believe that neither an Init Container nor a PostStart hook is need. For some time now the agent supports running the `netdata-claim.sh` script during startup, if the appropriate command line parameters are passed to it. This is documented here:
https://learn.netdata.cloud/docs/agent/claim#newephemeral-agent-containers

So, all that is needed is to pass the right parameters to the main container's entrypoint script.

**Comment by knatsakis** [comment]
If the agent is already claimed the claiming script fails but the agent detects that it is already claimed and tries to establish a connection.

**Comment by ilyam8** [comment]
yeah, it works, i remember [i tested it](https://github.com/netdata/netdata/pull/9058)

do we need some persistent volume or [`persistUniqueID: true`](https://github.com/netdata/helmchart/blob/9626cec86ab775e084d2e6b92de36def3adbfb9c/values.yaml#L192) is enough?

**Comment by knatsakis** [comment]
Example run with an empty `/var/lib/netdata` volume (unclaimed agent):

```
docker run                                                               \
       --name netdata                                                    \
       -p 19999:19999                                                    \
       -v /tmp/netdata:/var/lib/netdata:rw                               \
       -v /proc:/host/proc:ro                                            \
       -v /sys:/host/sys:ro                                              \
       netdata/netdata:v1.23.1                                           \
       -W set2 cloud global enabled true                                 \
       -W set2 cloud global "cloud base url" "https://app.netdata.cloud" \
       -W "claim -token=\"${TOKEN}\" -rooms=\"${ROOMS}\" -url=\"${URL}\""


2020-07-09 13:49:53: netdata INFO  : MAIN : Host '3f112bb4eef3' (at registry as '3f112bb4eef3') with guid '11140564-c1eb-11ea-9e6b-0242ac110002' initialized, os 'linux', timezone 'UTC', tags '', program_name 'netdata', program_version 'v1.23.1', update every 1, memory mode dbengine, history entries 3996, streaming disabled (to '' with api key ''), health enabled, cache_dir '/var/cache/netdata', varlib_dir '/var/lib/netdata', health_log '/var/lib/netdata/health/health-log.db', alarms default handler '/usr/libexec/netdata/plugins.d/alarm-notify.sh', alarms default recipient 'root'
2020-07-09 13:49:53: netdata INFO  : MAIN : Executing agent claiming command 'netdata-claim.sh'
2020-07-09 13:49:53: netdata INFO  : MAIN : Waiting for claiming command to finish.
cli failed, assume netdata is not running and query the on-disk config
cli failed, assume netdata is not running and query the on-disk config
Token: ****************
Base URL: https://app.netdata.cloud
Id: 11140564-c1eb-11ea-9e6b-0242ac110002
Rooms: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Hostname: 3f112bb4eef3
Proxy:
Netdata user: netdata
Generating private/public key for the first time.
Generating RSA private key, 2048 bit long modulus (2 primes)
..............+++++
....................................................................................+++++
e is 65537 (0x010001)
Extracting public key from private key.
writing RSA key
2020-07-09 13:49:54: netdata INFO  : MAIN : Agent claiming command returned with code 0
```

Example run with a filled `/var/lib/netdata` volume (already claimed agent):

```
2020-07-09 13:52:35: netdata INFO  : MAIN : Host '97903060e7ae' (at registry as '97903060e7ae') with guid '11140564-c1eb-11ea-9e6b-0242ac110002' initialized, os 'linux', timezone 'UTC', tags '', program_name 'netdata', program_version 'v1.23.1', update every 1, memory mode dbengine, history entries 3996, streaming disabled (to '' with api key ''), health enabled, cache_dir '/var/cache/netdata', varlib_dir '/var/lib/netdata', health_log '/var/lib/netdata/health/health-log.db', alarms default handler '/usr/libexec/netdata/plugins.d/alarm-notify.sh', alarms default recipient 'root'
2020-07-09 13:52:35: netdata INFO  : MAIN : Executing agent claiming command 'netdata-claim.sh'
2020-07-09 13:52:35: netdata INFO  : MAIN : Waiting for claiming command to finish.
cli failed, assume netdata is not running and query the on-disk config
cli failed, assume netdata is not running and query the on-disk config
Token: ****************
Base URL: https://app.netdata.cloud
Id: 11140564-c1eb-11ea-9e6b-0242ac110002
Rooms: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Hostname: 97903060e7ae
Proxy:
Netdata user: netdata
2020-07-09 13:52:36: netdata ERROR : MAIN : child pid 158 exited with code 13.
2020-07-09 13:52:36: netdata INFO  : MAIN : Agent claiming command returned with code 13
2020-07-09 13:52:36: netdata ERROR : MAIN : Agent failed to be claimed with the following error message:
2020-07-09 13:52:36: netdata ERROR : MAIN : "already claimed" (errno 22, Invalid argument)
2020-07-09 13:52:36: netdata INFO  : MAIN : File '/var/lib/netdata/cloud.d/claimed_id' was found. Setting state to AGENT_CLAIMED.
```

**Comment by ilyam8** [comment]
so is it ok to have empty `/var/lib/netdata` but same `netdata.public.unique.id`? Cloud handles it?

**Comment by knatsakis** [comment]
> yeah, it works, i remember [i tested it](https://github.com/netdata/netdata/pull/9058)
> 
> do we need some persistent volume or [`persistUniqueID: true`](https://github.com/netdata/helmchart/blob/9626cec86ab775e084d2e6b92de36def3adbfb9c/values.yaml#L192) is enough?

We need to persist `/var/lib/netdata/cloud.d` in a way similar to https://github.com/netdata/helmchart/blob/9626cec86ab775e084d2e6b92de36def3adbfb9c/templates/daemonset.yaml#L153

I thought we were doing that for the children but it seems we don't.

**Comment by knatsakis** [comment]
> so is it ok to have empty `/var/lib/netdata` but same `netdata.public.unique.id` every time? Cloud handles it?

I believe we need to persist both `/var/lib/netdata/cloud.d` and `/var/lib/netdata/registry`

**Comment by ilyam8** [comment]
we dont really persist `/var/lib/netdata/registry/netdata.public.unique.id`, in fact we create in on start using init container

https://github.com/netdata/helmchart/blob/9626cec86ab775e084d2e6b92de36def3adbfb9c/templates/daemonset.yaml#L76-L86

`netdata.public.unique.id` is persistent because we use node object `uid` as `netdata.public.unique.id`

**Comment by lgg42** [comment]
Thanks for all this information! I didn't know! I'll continue to work on the PR with his update.

**Comment by cakrit** [comment]
The child nodes in the daemonset can't have a persistent volume. So we should only be claiming the parent.  We're currently working on getting streamed child node data to appear on the cloud, so we won't need to have the children claimed anyway.

Claiming the children every time the pod restarts wouldn't be problematic if we had chosen to let them always get a new identifier (MACHINE_GUID in `/var/lib/netdata/registry/netdata.public.unique.id`), but we chose to make that predictable in #61.
