### ISSUE TITLE
add some checks/linters

### ISSUE THREAD

**Issue by ilyam8** [netdata/helmchart#81]
We need to add some yaml/helm linters.

**Comment by ilyam8** [comment]
@ncmans could you recommend something?

**Comment by ilyam8** [comment]
i guess https://github.com/helm/chart-testing-action is ok

**Comment by prologic** [comment]
> i guess https://github.com/helm/chart-testing-action is ok

LGTM PR welcome :)

**Comment by knatsakis** [comment]
Fixed in #227
