### ISSUE TITLE
resources requests defaults

### ISSUE THREAD

**Issue by ilyam8** [netdata/helmchart#84]
I see both netdata master and slave have no resources requests defaults. I think it is wrong and we need to provide default values.

Requests needed by scheduler and it is good practice to not have empty resources.

Btw GKE has webhook `pod-ready.config.common-webhooks.networking.gke.io` and it (silently for you) sets resources.requests.cpu to 100m if it is not set.

___

Do you have something in defense of no resources defaults? @varyumin @knatsakis @ncmans

**Comment by ncmans** [comment]
@ilyam8 Helm charts don't tend to provide resource requests as defaults (only perhaps as a comment) to accomodate running the charts on resource limited environments (e.g. minikube). See helm's official recommendation when creating new helm charts:

```
$ helm create my-sample-chart
$ cd my-sample-chart
$ cat values.yaml
...
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
...
```

**Comment by ilyam8** [comment]
Well, it is very questionable approach in my opinion. If i would be an k8s cluster admin i would like not to have apps w/ `resources: {}`.

i was thinking that if you want to install something from helm you do `helm install`. But it seems you do it only for tests, the correct way is to download, change values and install after 🤔

**Comment by ilyam8** [comment]
I think that app developer knows better cpu/mem usage and can provide reasanoble defaults, it is better then provide nothing. Because scheduling is kind of broken without it.

Anyway if it is the official helm way lets follow it.

**Comment by ncmans** [comment]
>  If i would be an k8s cluster admin i would like not to have apps w/ `resources: {}`.

Absolutely! Running without resource requests will result in pod evictions left and right.

> But it seems you do it only for tests, the correct way is to download, change values and install after

That's correct. Unfortunately there isn't one value that can be regarded as fitting even the majority of use cases of a chart. So providing a default is kind of misleading the user to believe that they don't need to worry about it.

As an example, the same chart may be mission critical and must have high availability. The resource requests of this chart would be quite permissive and have plenty of headroom. In contrast, if the service isn't critical and cost is a consideration, lower requests should be set.

> I think that app developer knows better cpu/mem usage and can provide reasanoble defaults

I think we can provide some suggestions in a comment in the `values.yaml` (as some charts do). The difference between this and default is that the user has to explicitly take action, ensuring they've made a decision based on their requirements.

**Comment by ilyam8** [comment]
I think it is app specific and up to developers. I see pulsar guys set resources for all its componenets.

Example

https://github.com/apache/pulsar/blob/52ae1823dbcbef95637580c5f3568843232cd379/deployment/kubernetes/helm/pulsar/values.yaml#L221-L224

It would be crazy to not provide in their case 😄 

___

> I think we can provide some suggestions in a comment in the values.yaml (as some charts do).

yeah

**Comment by ilyam8** [comment]
We want netdata to be up and running and not be a target for a oom killer in the first place. 

To get that BestEffort class does not suit to us. 

> user has to explicitly take action

If we provide `resources: {}` as defaults we need to make it super explicit and say that **current defaults are not ok for production**.

**Comment by ncmans** [comment]
> I see pulsar guys set resources for all its components

Pulsar's chart is quite [experimental](https://github.com/apache/pulsar/issues/4687) and in-flux at the moment (and broken in many ways). I wouldn't use that as a prime example (been wrestling with it for sometime :grin:  ).

> If we provide resources: {} by default we need to make it super explicit and say that current defaults are not ok for production.

Something else that chart providers do is that they provide a `values-production.yaml` that has resource requests set and is somewhat production ready (or at least a good start). Users can then copy that and edit it. This option will provide less friction for the user.

**Comment by ilyam8** [comment]
@varyumin your thoughts on this?
