### ISSUE TITLE
netdata master: survive node failure

### ISSUE THREAD

**Issue by ilyam8** [netdata/helmchart#86]
Netdata master runs as `Statefulset`.

> https://kubernetes.io/docs/tasks/run-application/force-delete-stateful-set-pod/#statefulset-considerations

> StatefulSet ensures that, at any time, there is at most one Pod with a given identity running in a cluster.

It means that if the node with Netdata master is not available (network problems, power problems, etc) statefulset woudlnt be rescheduled on the other node of the cluster. Which bascially means no monitoring.

Related issues:
 - https://github.com/kubernetes/kubernetes/issues/54368
 - https://github.com/kubernetes/kubernetes/issues/74947

Suggested way to handle such kind of situation is manually delete the node from the cluster to get rescheduling statefulsets possible.

___

So, what is the best way to handle node with netdata master failure?

- Do not schedule netdata master on the worker node?
- Install netdata master outside of the cluster?

@knatsakis @ncmans

**Comment by unixfox** [comment]
With the release of netdata cloud, the master could be replaced by netdata cloud and all the nodes would have netdata as a daemonset connected to netdata cloud.
I don't know if it's a viable solution but from I can see netdata cloud seems to aggregate the metrics from multiple nodes so this kinda replace the functions of a netdata master.

**Comment by ilyam8** [comment]
It could be but current design doesnt allow it. Cloud doesnt store metrics.

**Comment by ncmans** [comment]
> So, what is the best way to handle node with netdata master failure?

One way is to deploy netdata master as a deployment with replica of 1 and deployment strategy of "replace".

**Comment by ilyam8** [comment]
i assume netdata doesn dns lookup only on connect, am i right? @stelfrag

**Comment by ilyam8** [comment]
i see they are `Recreate` and `RollingUpdate`

```
DESCRIPTION:
     Type of deployment. Can be "Recreate" or "RollingUpdate". Default is
     RollingUpdate.
```

> All existing Pods are killed before new ones are created when .spec.strategy.type==Recreate.


---

[StatefulSet](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#using-statefulsets)

```
- Stable, unique network identifiers.
- Stable, persistent storage.
- Ordered, graceful deployment and scaling.
- Ordered, automated rolling updates.

In the above, stable is synonymous with persistence across Pod (re)scheduling. If an application doesn’t require any stable identifiers or ordered deployment, deletion, or scaling, you should deploy your application using a workload object that provides a set of stateless replicas.
```

It looks like atm we dont need 3 and 4, 2 can be achieved using a deployment too. (@ncmans ?).

So the main blocker is 1.

**Comment by ncmans** [comment]
> So the main blocker is 1.

@ilyam8 

We have a kubernetes service that has a stable network identifier which sits in front of our pod. We don't really need the pod itself to have that property.

Something like a cluster of DB nodes that must directly talk to each other would require unique network id at the pod level, but netdata master is a single node app.

Also, corrections to previous comment. I meant deployment with recreate strategy (not replace).

**Comment by ilyam8** [comment]
oh, ofc, it is a service IP, not a pod 🙈 Then it looks like a deployment is a more reliable way to deploy nd master
