### ISSUE TITLE
Configmap size

### ISSUE THREAD

**Issue by sbillon** [netdata/helmchart#88]
Hello,

When I am trying to install netdata with helm, I get this message

`helm install netdata ./netdata
Error: create: failed to create: Secret "sh.helm.release.v1.netdata.v1" is invalid: data: Too long: must have at most 1048576 characters`

It looks configmap is bigger than the 1mb configmap allowed size

`helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}`

++

**Comment by ilyam8** [comment]
https://github.com/helm/helm/issues/6711

**Comment by lgg42** [comment]
Same error here, but with Helm 2

from tiller logs:
```
[storage/driver] 2020/04/23 16:15:15 create: failed to create: ConfigMap "netdata.v1" is invalid: []: Too long: must have at most 1048576 characters
[tiller] 2020/04/23 16:15:15 warning: Failed to record release netdata: ConfigMap "netdata.v1" is invalid: []: Too long: must have at most 1048576 characters
```

```
$ helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:32:32Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

using netdata Chart version: 1.1.14

**Comment by ilyam8** [comment]
Not a specialist but i think it is not netdata helmchart bug, i think we need to open an issue/find existing one in a helm reop

**Comment by ilyam8** [comment]
@knatsakis what do you think?

**Comment by lgg42** [comment]
Ok, I found the issue, the problem is the `.git` folder being too big and going in.
I did an `rm -rf .git` and I could install the chart without problems. Normally I install charts from helm repos so I didn't run into this problem before.

Maybe, as a solution, you could add to the README.md the step to `rm -rf .git` before installing the chart.

**Comment by ilyam8** [comment]
> Maybe, as a solution, you could add to the README.md the step to

`.helmignore` will do
