### ISSUE TITLE
Streaming issue, cannot resolve host netdata

### ISSUE THREAD

**Issue by zack-shoylev** [netdata/helmchart#94]
> We have re-installed k8s, and installed netdata with helm chart (v21) again. I have also set the persistent flags for alarm and database to true. But we still cannot access the slaves immediately. There are only 2 nodes: "netdata-master-0 & master"  So we still have streaming problem for slaves. And this is the log I receive from all workers:

> netdata ERROR : STREAM_SENDER[worker-2] : Cannot resolve host 'netdata', port '19999': Try again (errno 22, Invalid argument)

This discussion started here: https://github.com/netdata/netdata/issues/8847

**Comment by cakrit** [comment]
Let's continue this in 8847, I did a comment to clarify what we need to do.
